### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
@xiaodaigh I think you have not yet enabled travis and appveyor for this repo? Could you do that, and then close and reopen this PR to trigger builds? I copied this over from RCall, so fingers crossed this will do the trick...

**Review by xiaodaigh — APPROVED** [review]

**Comment by davidanthoff** [comment]
@xiaodaigh any chance you could switch Travis and appveyor on for this repo?

**Comment by davidanthoff** [comment]
@xiaodaigh Bump, this should really be very easy, you just need to enable Travis and AppVeyor for this repo and then close and open this PR. Shouldn’t be more than five minutes, and it would allow us to move forward here.

**Comment by xiaodaigh** [comment]
Ok thanks for your work. I am quite new to this stuff. I think it's working now and I didn't know how easy it was so I just put it off

**Comment by davidanthoff** [comment]
No problem, thanks! Now I just need to fix the builds :)

**Pull request merged**
