### PR TITLE
Rename package

### PR DESCRIPTION
**Pull request by davidanthoff**
This finishes the package rename. Also fixes doc building etc.

### CODE REVIEW

**Comment by davidanthoff** [comment]
@xiaodaigh Bump, any chance you could merge this and we could have another go at METADATA registration?

**Comment by davidanthoff** [comment]
@xiaodaigh Bump, what is your thinking about this? I want to wrap up some work on the whole file IO story in the Queryverse and it would be great to know whether I might be able to include this here or not.

**Comment by xiaodaigh** [comment]
it requires the fst packake to be installed to pass the tests and I don't how to do that on Appveyor and Travis CI

**Comment by MarcusKlik** [comment]
Hi @davidanthoff and @xiaodaigh, perhaps you could use the Travis script reported in [this stackoverflow thread](https://stackoverflow.com/questions/44904805/download-r-and-specific-package-as-travis-dependency)?

I have no experience with the Julia Travis setup, but it seems you can install `R` and `R` packages in the _before install_ section to be used by a `Julia` package later on.

Would be nice to get the Travis automatic build operational!

**Comment by davidanthoff** [comment]
@xiaodaigh Maybe we can merge this PR first, and then figure out how to get the CI builds running? The technique in that stackoverflow might work, and we can also just take a look how RCall.jl does it. But before any of that, we need to finish the rename, right?

**Review by xiaodaigh — APPROVED** [review]
awesome thanks

**Pull request merged**
